<?xml version='1.0' encoding='UTF-8' ?>
<testsuite tests="0" failures="0" errors="0" skipped="0" time="1.177" timestamp="2025-10-13T18:54:02" hostname="localhost">
  <properties>
    <property name="device" value="Pixel_9_Pro_XL(AVD) - 16" />
    <property name="flavor" value="" />
    <property name="project" value=":ShareConnector" />
  </properties>
  <system-err>Test run failed to complete. Instrumentation run failed due to Process crashed.
Logcat of last crash: 
Process: com.shareconnect.debug, PID: 10150
java.lang.IllegalAccessError: Method 'com.google.protobuf.LazyStringArrayList com.google.protobuf.LazyStringArrayList.emptyList()' is inaccessible to class 'digital.vasic.asinka.proto.HandshakeRequest' (declaration of 'digital.vasic.asinka.proto.HandshakeRequest' appears in /data/app/~~1Rjf7iWu2HM1YzNmASDC7w==/com.shareconnect.debug-OQuFdahMG26xFTAEFmsJtQ==/base.apk!classes3.dex)
	at digital.vasic.asinka.proto.HandshakeRequest.&lt;init&gt;(HandshakeRequest.java:232)
	at digital.vasic.asinka.proto.HandshakeRequest.&lt;clinit&gt;(HandshakeRequest.java:1795)
	at digital.vasic.asinka.proto.AsinkaServiceGrpc.getHandshakeMethod(AsinkaServiceGrpc.java:38)
	at digital.vasic.asinka.proto.AsinkaServiceGrpc.getServiceDescriptor(AsinkaServiceGrpc.java:489)
	at digital.vasic.asinka.proto.AsinkaServiceGrpcKt$AsinkaServiceCoroutineImplBase.bindService(AsinkaGrpcKt.kt:231)
	at io.grpc.internal.ServerImplBuilder.addService(ServerImplBuilder.java:143)
	at io.grpc.internal.ServerImplBuilder.addService(ServerImplBuilder.java:57)
	at io.grpc.ForwardingServerBuilder.addService(ForwardingServerBuilder.java:77)
	at digital.vasic.asinka.transport.GrpcTransport.startServer(GrpcTransport.kt:56)
	at digital.vasic.asinka.AsinkaClient.start(AsinkaClient.kt:74)
	at com.shareconnect.profilesync.ProfileSyncManager.start(ProfileSyncManager.kt:51)
	at com.shareconnect.SCApplication$initializeProfileSync$1.invokeSuspend(SCApplication.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:233)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:152)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$kotlinx_coroutines_core(CancellableContinuationImpl.kt:504)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$kotlinx_coroutines_core$default(CancellableContinuationImpl.kt:493)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:596)
	at kotlinx.coroutines.android.HandlerContext.scheduleResumeAfterDelay$lambda$1(HandlerDispatcher.kt:141)
	at kotlinx.coroutines.android.HandlerContext.$r8$lambda$1oICx0p9952ACqpdbT-DIvW6E9k(Unknown Source:0)
	at kotlinx.coroutines.android.HandlerContext$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:995)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:248)
	at android.os.Looper.loop(Looper.java:338)
	at android.app.ActivityThread.main(ActivityThread.java:9067)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}&#64;fc80e6, Dispatchers.Main]

</system-err>
</testsuite>